import { describe, expect, it } from "bun:test";
import { readFileSync } from "node:fs";
import path from "node:path";
import { collectApiRouteDocs } from "../src/http/api-docs";
import { generateApiReferenceMarkdown } from "../src/http/api-reference-markdown";
import { createAppRoutes } from "../src/http/app-routes";
import type { AppDeps } from "../src/types/app.types";

describe("api reference markdown", () => {
	it("renders grouped route documentation", () => {
		const markdown = buildApiReferenceMarkdown();

		expect(markdown.startsWith("# API Reference\n")).toBeTrue();
		expect(markdown).toContain("Generated by `bun run docs:api`");
		expect(markdown).toContain("Total endpoints: 61");
		expect(markdown).toContain("## Chat");
		expect(markdown).toContain("### POST `/api/chat/sessions/{id}/send`");
		expect(markdown).toContain("- Path params: `id`");
		expect(markdown).toContain("- Request body: Chat send payload.");
		expect(markdown).toContain("- Response: Accepted send status.");
	});

	it("keeps the committed API reference generated", () => {
		const referencePath = path.resolve(
			import.meta.dir,
			"../../../docs/api-reference.md",
		);

		expect(readFileSync(referencePath, "utf8")).toBe(
			buildApiReferenceMarkdown(),
		);
	});
});

function buildApiReferenceMarkdown(): string {
	return generateApiReferenceMarkdown(
		collectApiRouteDocs(createAppRoutes(createDeps())),
	);
}

function createDeps(): AppDeps {
	return {
		cliExecutor: {
			execute: async (request) => ({ status: "succeeded", request }),
			executeStream: async (request) => ({ status: "succeeded", request }),
			getHistory: () => [],
		},
	};
}
