import type { ApiRouteDoc } from "./types/api-docs.types";

const METHOD_RANKS = new Map([
	["GET", 0],
	["POST", 1],
	["PATCH", 2],
	["DELETE", 3],
]);

export function generateApiReferenceMarkdown(routes: ApiRouteDoc[]): string {
	const orderedRoutes = [...routes].sort(compareRouteDocs);
	const lines = [
		"# API Reference",
		"",
		"<!-- Generated by `bun run docs:api`. Do not edit by hand. -->",
		"",
		"Generated from server route metadata. Keep `openapi.yaml` aligned with these routes.",
		"",
		`Total endpoints: ${orderedRoutes.length}`,
		"",
	];

	for (const [group, groupRoutes] of groupRouteDocs(orderedRoutes)) {
		lines.push(`## ${group}`, "");
		for (const route of groupRoutes) {
			appendRouteLines(lines, route);
		}
	}

	return `${lines.join("\n")}\n`;
}

function groupRouteDocs(routes: ApiRouteDoc[]): [string, ApiRouteDoc[]][] {
	const docsByGroup = new Map<string, ApiRouteDoc[]>();
	for (const route of routes) {
		const groupRoutes = docsByGroup.get(route.group) ?? [];
		groupRoutes.push(route);
		docsByGroup.set(route.group, groupRoutes);
	}
	return [...docsByGroup.entries()].sort(([left], [right]) =>
		left.localeCompare(right),
	);
}

function appendRouteLines(lines: string[], route: ApiRouteDoc): void {
	lines.push(`### ${route.method} \`${route.path}\``, "", route.summary, "");
	if (route.pathParams?.length) {
		lines.push(`- Path params: ${formatNames(route.pathParams)}`);
	}
	if (route.queryParams?.length) {
		lines.push(`- Query params: ${formatNames(route.queryParams)}`);
	}
	if (route.requestBody) {
		lines.push(`- Request body: ${route.requestBody}`);
	}
	lines.push(`- Response: ${route.response}`, "");
}

function formatNames(names: string[]): string {
	return names.map((name) => `\`${name}\``).join(", ");
}

function compareRouteDocs(left: ApiRouteDoc, right: ApiRouteDoc): number {
	const groupOrder = left.group.localeCompare(right.group);
	if (groupOrder !== 0) {
		return groupOrder;
	}
	const pathOrder = left.path.localeCompare(right.path);
	if (pathOrder !== 0) {
		return pathOrder;
	}
	return methodRank(left.method) - methodRank(right.method);
}

function methodRank(method: ApiRouteDoc["method"]): number {
	return METHOD_RANKS.get(method) ?? METHOD_RANKS.size;
}
